name: Server Tests

on:
  push:
    branches:
      - main
      - babylon-version

jobs:
  testing:
    name: Server Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        
      - run: bun install
      - run: bun test